version: '3'

services: 
    api:
        build: 
            context: .
            dockerfile: Dockerfile
        command: bash -c "alembic upgrade head && uvicorn main:app --reload --workers 1 --host 0.0.0.0" 
        container_name: gainit_api
        restart: always
        ports:
            - 8001:8000
        depends_on: 
            - db
            - redis

    db:
        image: postgres
        restart: always
        volumes: 
            - postgres_data_local:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}

    redis:
        image: redis:6-alpine

    worker:
        build: .
        command: celery --app=tasks.worker.app worker -B --loglevel=info
        volumes:
            - ./project:/usr/src/app
        environment:
            - CELERY_BROKER_URL=redis://redis:6379/0
            - CELERY_RESULT_BACKEND=redis://redis:6379/0
        depends_on:
            - api
            - redis

    dashboard:
        build: .
        command: celery --app=tasks.worker.app --broker=redis://redis:6379/0  flower --port=5555
        ports:
            - 5556:5555
        environment:
            - CELERY_BROKER_URL=redis://redis:6379/0
            - CELERY_RESULT_BACKEND=redis://redis:6379/0
        depends_on:
            - api
            - redis
            - worker


volumes: 
    postgres_data_local: