export const FETCH_MEMBERSHIP_TYPE_REQUEST = "FETCH_MEMBERSHIP_TYPE_REQUEST"
export const FETCH_MEMBERSHIP_TYPE_SUCCESS = "FETCH_MEMBERSHIP_TYPE_SUCCESS"
export const FETCH_MEMBERSHIP_TYPE_FAIL = "FETCH_MEMBERSHIP_TYPE_FAIL"

export const FETCH_MEMBER_TYPES_REQUEST = "FETCH_MEMBER_TYPES_REQUEST"
export const FETCH_MEMBER_TYPES_SUCCESS = "FETCH_MEMBER_TYPES_SUCCESS"
export const FETCH_MEMBER_TYPES_FAIL= "FETCH_MEMBER_TYPES_FAIL"

export const ADD_MEMBERSHIP_TYPE_REQUEST = "ADD_MEMBER_TYPE_REQUEST"
export const ADD_MEMBERSHIP_TYPE_SUCCESS = "ADD_MEMBER_TYPE_SUCCESS"
export const ADD_MEMBERSHIP_TYPE_FAIL = "ADD_MEMBER_TYPE_FAIL"
