export const FETCH_ALL_MEMBERS_REQUEST = "FETCH_ALL_MEMBERS_REQUEST"
export const FETCH_ALL_MEMBERS_SUCCESS = "FETCH_ALL_MEMBERS_SUCCESS"
export const FETCH_ALL_MEMBERS_FAIL = "FETCH_ALL_MEMBERS_FAIL"

export const FETCH_SINGLE_MEMBER_REQUEST = "FETCH_SINGLE_MEMBER_REQUEST"
export const FETCH_SINGLE_MEMBER_SUCCESS = "FETCH_SINGLE_MEMBER_SUCCESS"
export const FETCH_SINGLE_MEMBER_FAIL = "FETCH_SINGLE_MEMBER_FAIL"

export const ADD_MEMBER_REQUEST = "ADD_MEMBER_REQUEST"
export const ADD_MEMBER_SUCCESS = "ADD_MEMBER_SUCCESS"
export const ADD_MEMBER_FAIL = "ADD_MEMBER_FAIL"