"""remove ismarried field

Revision ID: 29e9efa01e11
Revises: 69b1d76cbd04
Create Date: 2021-06-30 11:38:49.520101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29e9efa01e11'
down_revision = '69b1d76cbd04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('members', 'is_married')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('is_married', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
