"""email column in members

Revision ID: 2aa12b82ba6b
Revises: 3f7192b98798
Create Date: 2021-06-29 22:34:30.705585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2aa12b82ba6b'
down_revision = '3f7192b98798'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('email', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('members', 'email')
    # ### end Alembic commands ###
