"""created_at and updated_at payments

Revision ID: c1358758c580
Revises: 210c664b866f
Create Date: 2021-07-02 00:09:39.875175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1358758c580'
down_revision = '210c664b866f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('payments', sa.Column('update_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'update_at')
    op.drop_column('payments', 'created_at')
    # ### end Alembic commands ###
